### ISSUE TITLE
[Faction Request] Faction/Mod Title

### ISSUE THREAD

**Issue by MajBoggie** [MitchJC93/LRG-Fundamentals#22]
**Mod Name**
Project Opfor

**Mod Link**
https://steamcommunity.com/sharedfiles/filedetails/?id=735566597&searchtext=project+opfor

**Faction Names**
Islamic State - LOP_ISTS_OPF
Boko Haram - LOP_BH
Middle Eastern Militia - LOP_AM_OPF
**These class names should be right, but please double check before adding**

**Request Deadline**
I could do with this for my campaign on Lythium, so as soon as possible, cheers :)

**Additional Info**
I think it would benefit alot of people with this being added, as i know alot of units use these factions

**Comment by MitchJC93** [comment]
Added all @Project OPFOR factions to Spawn AI Module in 1.4.3
